---
sudo: required


services:
  - docker

before_install:
  # Fetch base image for testing
  - docker pull uriahfeng/docker-basic-image:7.7.1980

script:
  # Run container in detached state
  - docker run --detach --privileged --volume="${PWD}":/etc/ansible/roles/nginx:ro --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro uriahfeng/docker-jenkins-slave /usr/lib/systemd/systemd > /tmp/container_id
  # Check syntax of ansible playbook
  - docker exec "$(cat /tmp/container_id)" ansible-playbook /etc/ansible/roles/nginx/tests/test.yml --syntax-check
  # Run ansible playbook
  - docker exec "$(cat /tmp/container_id)" ansible-playbook /etc/ansible/roles/nginx/tests/test.yml
  # Clean up
  - docker stop "$(cat /tmp/container_id)"

notifications:
  email: false
