---
- name: Copy customized config instead of original config
  template:
    src: nginx.conf
    dest: "{{ nginx_path }}/nginx.conf"
    mode: 0644
  tags:
    - package
    - config

- name: Check the directory which it saves config files is existence or not
  stat:
    path: "{{ nginx_path }}/conf.d"
  register: ch_confd
  tags:
    - package
    - config

- name: Create a directory to reserve all configurations if it is not existence
  file:
    path: "{{ nginx_path }}/conf.d"
    state: directory
    mode: 0755
  when: ch_confd.stat.exists == False
  tags:
    - package
    - config

- name: Check the directory which it saves extra configurations is existence or not
  stat:
    path: "{{ nginx_path }}/conf.d/include"
  register: ch_inc
  tags:
    - package
    - config

- name: Create a directory to reserve all extra configurations if it is not existence
  file:
    path: "{{ nginx_path }}/conf.d/include"
    state: directory
    mode: 0755
  when: ch_inc.stat.exists == False
  tags:
    - package
    - config

- name: Add extra configurations into the destination
  template:
    src: "{{ item }}"
    dest: "{{ nginx_path }}/conf.d/include/{{ item | basename | regex_replace('^(\\w+).j2', '\\1') }}"
  with_fileglob:
    - "../templates/include/*.j2"
  tags:
    - package
    - config

- name: Check the directory which it saves links is existence or not
  stat:
    path: "{{ nginx_path }}/sites-enabled"
  register: ch_se
  tags:
    - package
    - config

- name: Create a directory to reserve all links if it is not existence
  file:
    path: "{{ nginx_path }}/sites-enabled"
    state: directory
    mode: 0755
  when: ch_se.stat.exists == False
  tags:
    - package
    - config

- name: Copy a default configuration to conf directory
  copy:
    src: example.conf
    dest: "{{ nginx_path }}/conf.d"
    mode: 0644
  tags:
    - package
    - config

- name: Check the directory which it saves files of caching is existence or not
  stat:
    path: "{{ nginx_cache_path }}/nginx"
  register: ch_cah
  tags:
    - package
    - config

- name: Create a directory to reserve caches if it is not existence
  file:
    path: "{{ nginx_cache_path }}/nginx"
    state: directory
    mode: 0755
  when: ch_cah.stat.exists == False
  tags:
    - package
    - config

- name: Mount up tmpfs using memory disk for caching
  mount:
    path: "{{ nginx_cache_path }}/nginx"
    src: tmpfs
    fstype: tmpfs
    opts: "defaults,size={{ nginx_cache_size }}"
    state: mounted
  when: ansible_virtualization_type != 'docker'
  tags:
    - package
    - config
