---
- name: Download GeoLite Country Database
  get_url:
    url: http://geolite.maxmind.com/download/geoip/database/GeoLiteCountry/GeoIP.dat.gz
    dest: "{{ nginx_temp_installation }}/GeoIP.dat.gz"
    mode: 0644
  tags:
    - package
    - config

- name: Update GeoLite Country Database
  shell: |
    gzip -d {{ nginx_temp_installation }}/GeoIP.dat.gz
    mv -f {{ nginx_temp_installation }}/GeoIP.dat {{ geoip_data_path }}/GeoIP-initial.dat
  tags:
    - package
    - config

- name: Download GeoLite Country IPv6 Database
  get_url:
    url: http://geolite.maxmind.com/download/geoip/database/GeoIPv6.dat.gz
    dest: "{{ nginx_temp_installation }}/GeoIPv6.dat.gz"
    mode: 0644
  tags:
    - package
    - config

- name: Update GeoLite Country IPv6 Database
  shell: |
    gzip -d {{ nginx_temp_installation }}/GeoIPv6.dat.gz
    mv -f {{ nginx_temp_installation }}/GeoIPv6.dat {{ geoip_data_path }}/GeoIPv6-initial.dat
  tags:
    - package
    - config

- name: Download GeoLite City Database
  get_url:
    url: http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz
    dest: "{{ nginx_temp_installation }}/GeoLiteCity.dat.gz"
    mode: 0644
  tags:
    - package
    - config

- name: Update GeoLite City Database
  shell: |
    gzip -d {{ nginx_temp_installation }}/GeoLiteCity.dat.gz
    mv -f {{ nginx_temp_installation }}/GeoLiteCity.dat {{ geoip_data_path }}/GeoIPCity-initial.dat
  tags:
    - package
    - config

- name: Download GeoLite City IPv6 Database
  get_url:
    url: http://geolite.maxmind.com/download/geoip/database/GeoLiteCityv6-beta/GeoLiteCityv6.dat.gz
    dest: "{{ nginx_temp_installation }}/GeoLiteCityv6.dat.gz"
    mode: 0644
  tags:
    - package
    - config

- name: Unarchive GeoLite City IPv6 Database
  shell: |
    gzip -d {{ nginx_temp_installation }}/GeoLiteCityv6.dat.gz
    mv -f {{ nginx_temp_installation }}/GeoLiteCityv6.dat {{ geoip_data_path }}/GeoIPv6-initial.dat
  tags:
    - package
    - config

- name: Download GeoLite ASN Database
  get_url:
    url: http://download.maxmind.com/download/geoip/database/asnum/GeoIPASNum.dat.gz
    dest: "{{ nginx_temp_installation }}/GeoIPASNum.dat.gz"
    mode: 0644
  tags:
    - package
    - config

- name: Update GeoLite ASN Database
  shell: |
    gzip -d {{ nginx_temp_installation }}/GeoIPASNum.dat.gz
    mv -f {{ nginx_temp_installation }}/GeoIPASNum.dat {{ geoip_data_path }}/GeoIPASNum-initial.dat
  tags:
    - package
    - config

- name: Download GeoLite ASN IPv6 Database
  get_url:
    url: http://download.maxmind.com/download/geoip/database/asnum/GeoIPASNumv6.dat.gz
    dest: "{{ nginx_temp_installation }}/GeoIPASNumv6.dat.gz"
    mode: 0644
  tags:
    - package
    - config

- name: Update GeoLite ASN IPv6 Database
  shell: |
    gzip -d {{ nginx_temp_installation }}/GeoIPASNumv6.dat.gz
    mv -f {{ nginx_temp_installation }}/GeoIPASNumv6.dat {{ geoip_data_path }}/GeoIPASNumv6-initial.dat
  tags:
    - package
    - config
