---
- name: Patch system kernel directives into /etc/sysctl.conf
  copy:
    src: sysctl.conf
    dest: /etc/sysctl.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  tags:
    - package
    - config

- name: Active all directives
  shell: |
    /sbin/sysctl -p
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"
  ignore_errors: yes
  tags:
    - package
    - config
