---
- name: Add waf libraries into the destination
  synchronize:
    src: lua
    dest: "{{ nginx_path }}"
    dirs: yes
  tags:
    - package

- name: Change directory onwer
  file:
    path: "{{ nginx_path }}/lua"
    owner: root
    group: root
    state: directory
  tags:
    - package

- name: Copy the configuration of waf to the destination
  template:
    src: waf.conf
    dest: "{{ nginx_path }}/waf.conf"
    mode: 0644
  tags:
    - package

- name: Check the file existence or not
  stat:
    path: "{{ nginx_path }}/logs/waf.log"
  register: ch_waf
  tags:
    - package

- name: Create a file to record all logs if it is not existence
  file:
    path: "{{ nginx_path }}/logs/waf.log"
    owner: root
    group: root
    state: touch
    mode: 0666
  when: ch_waf.stat.exists == False
  tags:
    - package
  
